### ISSUE TITLE
Click Here

### ISSUE THREAD

**Issue by discospiff** [mikeal200/MoodyBluez#39]
"Click Here" is very 90s.  I'd just say, "Home" in the link text.  Or just direct them to the top nav.

https://github.com/mikeal200/MoodyBluez/blob/9d7d92bf2f884543894d36d4cef02181d737e626/src/main/resources/templates/error.html#L17

**Comment by mikeal200** [comment]
fixed <h4><a th:href="@{/}">Home</a></h4>
